name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    env:
      CARGO_INCREMENTAL: 1
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: lint
        run: cargo clippy

  build:
    env:
      CARGO_INCREMENTAL: 1
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose

  test:
    needs: build
    env:
      CARGO_INCREMENTAL: 1
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test

