name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        path: ~/caches
        key: ${{ runner.os }}-rust-${{ hashFiles(‘target’) }}
        restore-keys: |
          ${{ runner.os }}-rust-
    - name: lint
      run: cargo clippy

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        path: ~/caches
        key: ${{ runner.os }}-rust-${{ hashFiles(‘target’) }}
        restore-keys: |
          ${{ runner.os }}-rust-
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        path: ~/caches
        key: ${{ runner.os }}-rust-${{ hashFiles(‘target’) }}
        restore-keys: |
          ${{ runner.os }}-rust-
    - name: Run tests
      run: cargo test

