name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: lint
      run: cargo clippy

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test

